from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate

# 1. Define the desired JSON structure for the comparison
class ComparisonOutput(BaseModel):
    similarity_score: int = Field(description="A score from 0 to 100 indicating how similar the two answers are.")
    explanation: str = Field(description="A brief 1-2 sentence explanation of what differed or if they matched completely.")

# 2. Initialize the local evaluator model
evaluator_llm = ChatOllama(model="qwen2.5-coder:3b", temperature=0)

# 3. Create the evaluation prompt
compare_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an expert evaluator. Compare two answers generated by different RAG pipelines for the same question.
    Determine how semantically similar they are on a scale of 0 to 100.
    100 = They convey the exact same factual information.
    0 = They are completely contradictory or cover totally different facts.
    Output JSON only."""),
    ("human", """Question: {question}
    
    Answer 1 (Custom): {answer_1}
    
    Answer 2 (Standard): {answer_2}""")
])

# 4. Chain it together
compare_chain = compare_prompt | evaluator_llm.with_structured_output(ComparisonOutput)